/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.cs.unicam.pa2022.logo.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
